### ISSUE TITLE
Invalid Plugin Error

### ISSUE THREAD

**Issue by kevnflores** [PluginsOCSInventory-NG/bitlockerstatus#1]
I was able to download this plugin from the releases page. I uploaded the plugin to OCS but receive the following error. 

ERROR: v1 is an invalid plugin, check your sources.
Installation aborted !

Also, the plugin returns a 404 error on OCS site. 
http://plugins.ocsinventory-ng.org/

**Comment by steph78630** [comment]
Hi @kevnflores ,

I just updated the sources, please can you try again ?

Thank you for using the plugins for OCS Inventory NG !

Kinds regards, Stephane
